# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vtktVRFCvh7BT57a13qOYifVcTm5oSi4
"""

#Assignment: Take multiple numbers through input and print the sum of the numbers.
x = [ int(i) for i in input('Enter values').split()]

s = 0
for j in x:
  s += j

print(s)